import { AntdRegistry } from '@ant-design/nextjs-registry'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { ReactQueryProvider } from '@/core/providers/ReactQueryProvider'
import StoreProvider from '@/core/providers/StoreProvider'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<ReactQueryProvider>
					<StoreProvider>
						<AntdRegistry>{children}</AntdRegistry>
					</StoreProvider>
				</ReactQueryProvider>
			</body>
		</html>
	)
}
